import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { MyChart } from '../pages/src/comp/MyChart'
import styles from '../styles/Home.module.css'
import { CircularProgress, Box } from '@mui/material'
import Axios from 'axios'

export default function Home() {
  const [chk, setChk] = useState(true);
  const [list, setList] = useState([302, 199, 209, 694, 249, 495, 300]);
  const API_URL = "http://localhost:5000/evChart";

  let config = {
    headers: {
        'Content-Type':'application/json',
        'Access-Control-Allow-Origin':'*'
    }
  };

  function getData(){
    Axios.post(
        API_URL,
        config
    ).then((res) =>{
        //console.log(res);
        setList(res.data);
        setChk(false); 
    });
  }

  useEffect(() => { //최초 한번만 호출하기 위해 사용함!
      getData();
  },[]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {chk && (
        <Box sx={{ display: 'flex' }}>
          <CircularProgress determinate='true' sx={{margin: '0 auto'}}/>
        </Box>
      )}
      {!chk && (
        <div style={{ width: '80%', margin: '0 auto'}}>
          <MyChart list={list}/>
        </div>
      )}
      
    </div>
  )
}
